### ISSUE TITLE
how to solve invalid keystore format error in android studio 2.2

### ISSUE THREAD

**Issue by palashmandokhot** [rsertelon/android-keystore-recovery#18]
how to solve invalid keystore format error in android studio 2.2

**Comment by rsertelon** [comment]
Once again, this issue has nothing to do with my project. Please stop opening issues here, I won't be able to help you. Use http://stackoverflow.com instead.

Thanks.

**Comment by palashmandokhot** [comment]
i post in stackoverflow but anyone not answering me
